In [1]:
# Added libraries.
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.window import Window
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 60)

spark = SparkSession.builder.master("local[*]")\
.config("spark.executor.memory", "10G")\
.config("spark.driver.memory", "10G")\
.config("spark.memory.fraction", ".8")\
.getOrCreate()

In [2]:
defun = spark.read.csv('../datos/defun_2016.csv', header =True) 
causas = spark.read.csv('../datos/decatcausa.csv', header =True) 
estados = spark.read.csv('../datos/decateml.CSV', header =True) 
genero = spark.read.csv('../datos/desexo.csv', header =True) 
edad = spark.read.csv('../datos/deedad.csv', header =True) 
escolaridad = spark.read.csv('../datos/deesco.csv', header =True)

In [3]:
for colum in defun.columns:
    defun = defun.withColumn(colum, regexp_replace(colum, '\t', ''))
    
numerics = ['anio_ocur','horas','anio_nacim']

for colum in numerics:
    defun = defun.withColumn(colum, col(colum).cast("double"))

In [4]:
estados = estados.withColumn('cve_ent', regexp_replace('cve_ent', '\t', ''))\
.withColumn('cve_mun', regexp_replace('cve_mun', '\t', '')).filter('cve_mun == 000')

In [5]:
defun_base = defun.alias('a').join(escolaridad.alias('b'), col('a.escolarida') == col('b.CVE'))\
.withColumn('edad', defun.anio_ocur - defun.anio_nacim)\
.filter('edad < 300').filter('edad > 0').filter('horas < 24').filter('escolarida < 24')\
.withColumn('id', monotonically_increasing_id())\
.withColumn("anios_edu", col("anios_edu").cast("double"))\
.drop('escolarida')

In [6]:
defun_base.limit(10).toPandas()

,ent_regis,mun_regis,ent_resid,mun_resid,tloc_resid,loc_resid,ent_ocurr,mun_ocurr,tloc_ocurr,loc_ocurr,causa_def,lista_mex,sexo,edad,dia_ocurr,mes_ocurr,anio_ocur,dia_regis,mes_regis,anio_regis,dia_nacim,mes_nacim,anio_nacim,ocupacion,edo_civil,presunto,ocurr_trab,lugar_ocur,necropsia,asist_medi,...,nacionalid,derechohab,embarazo,rel_emba,horas,minutos,capitulo,grupo,lista1,gr_lismex,vio_fami,area_ur,edad_agru,complicaro,dia_cert,mes_cert,anio_cert,maternas,lengua,cond_act,par_agre,ent_ocules,mun_ocules,loc_ocules,razon_m,dis_re_oax,CVE,DESCRIP,anios_edu,id
0,01,003,01,001,15,0001,01,001,15,0001,C539,12A,2,55.0,31,12,1993.0,26,10,2016,3,5,1938.0,11,3,8,8,88,9,1,...,1,99,8,8,20.0,30,2,8,037,12,8,1,16,8,99,10,2016,None,9,2,88,88,888,8888,0,999,1,Sin escolaridad,0.0,0
1,01,001,01,006,8,0001,01,001,15,0001,I259,28Z,2,75.0,7,5,2010.0,12,2,2016,7,4,1935.0,11,5,8,8,88,2,1,...,1,3,8,8,15.0,19,9,4,067,28,8,1,20,8,99,2,2016,None,9,2,88,88,888,8888,0,999,3,Primaria incompleta,5.0,1
2,01,001,01,010,1,7777,01,010,1,7777,K729,35M,2,70.0,3,11,2010.0,30,8,2016,16,6,1940.0,11,5,8,8,88,9,1,...,1,1,8,8,9.0,0,11,8,080,35,8,2,19,8,99,8,2016,None,9,2,88,88,888,8888,0,999,3,Primaria incompleta,5.0,2
3,01,001,01,001,1,0444,01,001,1,7777,E112,20D,2,54.0,17,11,2007.0,9,9,2016,2,8,1953.0,11,5,8,8,88,2,1,...,1,1,9,9,5.0,0,4,2,052,20,8,2,15,9,99,9,2016,None,9,2,88,88,888,8888,0,999,1,Sin escolaridad,0.0,3
4,01,006,01,006,8,0001,01,006,8,0001,X590,51Z,2,81.0,30,12,2015.0,8,1,2016,23,11,1934.0,11,5,1,2,9,9,1,...,1,2,8,8,17.0,30,20,25,103,E51,8,1,21,8,30,12,2015,None,2,2,88,88,888,8888,0,999,9,Profesional,18.0,4
5,01,001,01,001,15,0001,01,001,15,0001,E110,20D,1,58.0,3,9,2015.0,12,1,2016,20,10,1957.0,2,5,8,8,88,2,1,...,1,1,8,8,17.0,20,4,2,052,20,8,1,16,8,3,9,2015,None,2,1,88,88,888,8888,0,999,5,Secundaria incompleta,9.5,5
6,01,001,01,001,15,0001,01,001,15,0001,E102,20D,2,37.0,24,12,2015.0,6,1,2016,14,5,1978.0,11,4,8,8,88,9,1,...,1,2,9,9,6.0,30,4,2,052,20,8,1,12,9,24,12,2015,None,2,2,88,88,888,8888,0,999,4,Primaria completa,8.0,6
7,01,001,01,001,15,0001,01,001,15,0001,I110,27A,2,68.0,11,12,2015.0,12,1,2016,19,12,1947.0,11,3,8,8,88,9,1,...,1,7,8,8,23.0,2,9,3,066,27,8,1,18,8,12,12,2015,None,2,2,88,88,888,8888,0,999,4,Primaria completa,8.0,7
8,01,001,01,001,15,0001,01,001,15,0001,G710,23Z,1,12.0,18,12,2015.0,4,1,2016,24,2,2003.0,11,1,8,8,88,2,1,...,1,7,8,8,13.0,35,6,9,061,23,8,1,07,8,18,12,2015,None,2,2,88,88,888,8888,0,999,4,Primaria completa,8.0,8
9,01,001,01,001,15,0001,01,001,15,0001,C719,13A,1,55.0,27,12,2015.0,5,1,2016,14,1,1960.0,7,5,8,8,88,2,1,...,1,3,8,8,20.0,0,2,11,042,13,8,1,16,8,27,12,2015,None,2,1,88,88,888,8888,0,999,6,Secundaria completa,11.0,9

Elegimos utilizar las variables de edad y anios de educación para ejecutar el modelo de k-means pues son la que identificamos que mejor separan las observaciones en causas de defunción. Intentamos ejecutar el modelo con otras combinaciones de variables, por ejemplo: incluyendo año de defunción y hora de defunción pero vimos que no eran informativas y metían ruido en los clústers. Además, elegimos utilizar 4 clústers porque, bajo nuestro objetivo de segmentar las causas de defunción, lograbamos la mayor heterogeneidad de causas entre los clusters.

In [7]:
features = ['edad','anios_edu']

In [8]:
from pyspark.ml.clustering import KMeans
from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml.evaluation import ClusteringEvaluator
from pyspark.ml import Pipeline

In [9]:
scaler = StandardScaler(inputCol='grouped_features', outputCol= 'features', withMean=True)
assembler = VectorAssembler(inputCols = features, outputCol = 'grouped_features')
kmeans = KMeans(k=4, seed=1)
pipe = Pipeline(stages = [assembler, scaler, kmeans])

In [10]:
model = pipe.fit(defun_base).transform(defun_base)

Como métrica adicional para evaluar nuestro modelo utilizamos la función de Clustering Evaluator, que calcula la medida de Silueta utilizando la distancia Euclidiana cuadrada. Su valor va de -1 a 1 y un valor más cercano a uno indica una mejor separación entre los grupos y menor separación entre los grupos.  

Obtuvimos un valor de 0.51, que es relativamente bueno.

In [11]:
evaluator = ClusteringEvaluator()
evaluator.evaluate(model)

0.510201158314592

El modelo separó los datos en 4 grupos. El número de registros en cada uno se muestra a continuación:

In [12]:
grupos = model.groupBy('prediction').count()
grupos.repartition(1).write.csv('res_local/a/', header = True)
grupos.show()

+----------+------+
|prediction| count|
+----------+------+
|         1|228120|
|         3| 75180|
|         2|120882|
|         0|193615|
+----------+------+

El modelo segmentó por edades, generando un grupo de 'jóvenes' (grupo 2) y 3 de adultos mayores:

In [13]:
print("Analisis Descriptivo para Edad")
edades = model.groupBy('prediction').agg((mean(model.edad)).alias('Promedio'),\
                                      (stddev(model.edad)).alias('Desviación'),\
                                     (max(model.edad)).alias('Máximo'),\
                                     (min(model.edad)).alias('Mínimo')).sort('prediction')
edades.repartition(1).write.csv('res_local/b/', header = True)
edades.show()

Analisis Descriptivo para Edad
+----------+-----------------+------------------+------+------+
|prediction|         Promedio|        Desviación|Máximo|Mínimo|
+----------+-----------------+------------------+------+------+
|         0|82.50203238385456|10.631032727375162| 114.0|  47.0|
|         1|71.05030685604068|10.257511135596726| 112.0|  49.0|
|         2| 36.0528697407389|12.151160044491256|  55.0|   1.0|
|         3|65.69436020218143|14.096422277095325| 112.0|  26.0|
+----------+-----------------+------------------+------+------+

En cuanto a años de estudio, hay un grupo de 'alta educación' (grupo 3), uno de baja educación que corresponde con el de los más ancianos (grupo 0). Como intermedios están el grupo 1 y 2.

In [14]:
print("Analisis Descriptivo para años de estudio")
estudio = model.groupBy('prediction').agg((mean(model.anios_edu)).alias('Promedio'),\
                                      (stddev(model.anios_edu)).alias('Desviación'),\
                                     (max(model.anios_edu)).alias('Máximo'),\
                                     (min(model.anios_edu)).alias('Mínimo')).sort('prediction')
estudio.repartition(1).write.csv('res_local/c/', header = True)
estudio.show()

Analisis Descriptivo para años de estudio
+----------+------------------+------------------+------+------+
|prediction|          Promedio|        Desviación|Máximo|Mínimo|
+----------+------------------+------------------+------+------+
|         0|1.8650930971257391|2.4306767893204864|   8.0|   0.0|
|         1| 7.269588374539716| 2.078462434217759|  12.5|   2.0|
|         2| 9.174533842921196| 3.834743961272716|  20.0|   0.0|
|         3| 16.42151503059324| 2.182663174870741|  20.0|  12.5|
+----------+------------------+------------------+------+------+

En cuanto a diferenciación en las enfermedades de cada grupo, estas varían y se pueden explicar por las diferencias en edad promedio en los grupos. Por ejemplo, la principal causa de muerte en el grupo de los jóvenes es la violencia. Mientras que la de mayor incidencia en los otros es infarto. En el grupo de mayor edad aparecen enfermedades respiratorias como otras causas comunes. En los grupos intermedios aparece la cirrosis como una causa común.

In [15]:
causas_por_grupo = model.alias('a').groupBy('prediction','a.causa_def').count()\
.select("*",dense_rank().over(Window.partitionBy('prediction').orderBy(desc('count'))).alias('rn'))\
.filter('rn < 6').join(causas.alias('b'), col('a.causa_def') == col('b.CVE')).drop('causa_def','CVE')
causas_por_grupo.repartition(1).write.csv('res_local/d/', header = True)

In [16]:
causas_por_grupo.show()

+----------+-----+---+--------------------+
|prediction|count| rn|             DESCRIP|
+----------+-----+---+--------------------+
|         1|31592|  1|Infarto agudo del...|
|         1|14498|  2|Diabetes mellitus...|
|         1|13604|  3|Diabetes mellitus...|
|         1| 6526|  4|Diabetes mellitus...|
|         1| 6445|  5|Otras cirrosis de...|
|         3|10463|  1|Infarto agudo del...|
|         3| 3282|  2|Diabetes mellitus...|
|         3| 3150|  3|Diabetes mellitus...|
|         3| 1850|  4|Otras cirrosis de...|
|         3| 1810|  5|Neumonía, no espe...|
|         2| 6816|  1|Agresión con disp...|
|         2| 6683|  2|Infarto agudo del...|
|         2| 3775|  3|Cirrosis hepática...|
|         2| 3065|  4|Otras cirrosis de...|
|         2| 3027|  5|Diabetes mellitus...|
|         0|35514|  1|Infarto agudo del...|
|         0| 9656|  2|Diabetes mellitus...|
|         0| 7131|  3|Enfermedad pulmon...|
|         0| 6638|  4|Diabetes mellitus...|
|         0| 5508|  5|Neumonía, no espe...|
+----------+-----+---+--------------------+

Como se puede observar en la tabla anterior, las causas de muerte varían en los diferentes grupos pues la edad esta claramente correlacionada con la causa de muerte. Por ejemplo, el grupo 2, correspondiente a los jóvenes, muestra causas relacionadas con violencia y accidentes. Mientras que en los grupos de mayor edad promedio están relacionadas con enfermedades. Por otro lado, dentro de estos grupos, las enfermedades también varían, por ejemplo, con el grupo 0, que es el de edad promedio de 85, las causas de muerte se diferencian de los otros por incluir problemas respiratorios.

In [17]:
causas_por_estado = model.alias('a').groupBy('prediction','a.ent_ocurr').count()\
.select("*",dense_rank().over(Window.partitionBy('prediction').orderBy(desc('count'))).alias('rn'))\
.filter('rn < 6').join(estados.alias('b'), col('a.ent_ocurr') == col('b.cve_ent')).drop('ent_ocurr','cve_ent','cve_loc','cve_mun')
causas_por_estado.repartition(1).write.csv('res_local/e/', header = True)

In [18]:
causas_por_estado.show()

+----------+-----+---+--------------------+
|prediction|count| rn|             nom_loc|
+----------+-----+---+--------------------+
|         1|29030|  1|    Ciudad de M�xico|
|         1|25784|  2|              M�xico|
|         1|17475|  3|Veracruz de Ignac...|
|         1|16108|  4|             Jalisco|
|         1|11354|  5|              Puebla|
|         3|16082|  1|    Ciudad de M�xico|
|         3| 7708|  2|              M�xico|
|         3| 5233|  3|             Jalisco|
|         3| 4329|  4|Veracruz de Ignac...|
|         3| 4279|  5|          Nuevo Le�n|
|         2|13563|  1|              M�xico|
|         2|11535|  2|    Ciudad de M�xico|
|         2| 8419|  3|             Jalisco|
|         2| 7979|  4|Veracruz de Ignac...|
|         2| 6392|  5|          Guanajuato|
|         0|19065|  1|              M�xico|
|         0|17871|  2|Veracruz de Ignac...|
|         0|12864|  3|    Ciudad de M�xico|
|         0|12564|  4|              Puebla|
|         0|12515|  5|             Jalisco|
+----------+-----+---+--------------------+

No hay mucha diferenciación en los estados donde ocurren los decesos, como es de esperar en todos los grupos se encuentra la Ciudad de México y el Estado de México en los primeros lugares.

In [19]:
pc_mujeres = model.groupBy('prediction').agg((mean(model.sexo)-1).alias('% mujeres')).sort('prediction')
pc_mujeres.repartition(1).write.csv('res_local/f/', header = True)
pc_mujeres.show()

+----------+-------------------+
|prediction|          % mujeres|
+----------+-------------------+
|         0| 0.5522867546419441|
|         1|0.46498772575837277|
|         2| 0.3111794973610629|
|         3| 0.3628624634211226|
+----------+-------------------+

Es interesante notar que en el grupo de los más jóvenes (grupo 2), donde las causas de muerte están relacionadas con violencia, únicamente 3 de cada 10 muertes son mujeres. Esta proporción va aumentando junto con el rango de edades, que se puede explicar a que, dado que las mujeres tienen mayor esperanza de vida, la proporción de mujeres del total de la población va aumentando con la edad.

In [20]:
print("Analisis Descriptivo para Horas de Defunción")
horas = model.groupBy('prediction').agg((mean(model.horas)).alias('Promedio'),\
                                      (stddev(model.horas)).alias('Desviación'),\
                                     (max(model.horas)).alias('Máximo'),\
                                     (min(model.horas)).alias('Mínimo')).sort('prediction')
horas.repartition(1).write.csv('res_local/g/', header = True)
horas.show()

Analisis Descriptivo para Horas de Defunción
+----------+------------------+------------------+------+------+
|prediction|          Promedio|        Desviación|Máximo|Mínimo|
+----------+------------------+------------------+------+------+
|         0|11.847713245358056| 6.655735518907808|  23.0|   0.0|
|         1|11.779835174469577|6.7044497641270775|  23.0|   0.0|
|         2|11.810310881686272| 6.942796085817443|  23.0|   0.0|
|         3|11.758752327746741| 6.740627504300753|  23.0|   0.0|
+----------+------------------+------------------+------+------+

No hay diferencia en esta variable.

### Análisis de resultados:

Elegimos utilizar 4 grupos porque observamos que con esta configuración se logra hacer una separación de las observaciones en grupos característicos, diferenciados principalmente por la variable 'edad' y por ende, de causas de muerte. La variable de año no aporta información para segmentar, pues más del 90% de las observaciones ocurrieron en 2015 y 2016.